server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    datasource:
      url: "${app.datasource.mysql.url}"
      username: "${app.datasource.mysql.username}"
      password: "${app.datasource.mysql.password}"
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      open-in-view: false
      database: mysql
      generate-ddl: false
      properties:
        hibernate:
          format_sql: true

logging.level:
  org.hibernate:
    SQL: debug